### ISSUE TITLE
Add by identifier "magic wand button"

### ISSUE THREAD

**Issue by FlorianPargent** [lmu-osc/introduction-to-zotero#10]
Personally, I think the most accurate and still very fast way to add scientific articles to zotero is to use "Add by itentifier" (the magic wand button in the toolbar) and insert the DOI, which should always be easily available if you read a published article or something like an arxiv preprint. These days, I exclusively use this option because in my experience 1) the Zotero connector seems to make more mistakes and does not get all entries correct, and 2) google scholar still does not know DOIs which are always required when I publish my own research in APA style and I would have to insert them manually afterwards.

**Comment by NeuroShepherd** [comment]
Thanks @FlorianPargent! I had not personally used this approach before, but we should definitely add it in as a higher priority option than the manual entry method I included.

**Comment by NeuroShepherd** [comment]
Closed in #18
