### ISSUE TITLE
'YAML of your file.'

### ISSUE THREAD

**Issue by MalikaIhle** [lmu-osc/introduction-to-zotero#13]
https://lmu-osc.github.io/introduction-to-zotero/citations_in_quarto.html : Citations in Quarto. ' This bibliography file will be automatically updated to include any new citations you add, and it will automatically generate the bibliography in the format you specify in the YAML of your file.' 

-> perhaps say in the YAML header of your quarto file?

**Comment by MalikaIhle** [comment]
in the next paragraph it says 'the yaml header of your file.' -> perhaps standardise to YAML header of your file

**Comment by MalikaIhle** [comment]
in https://lmu-osc.github.io/introduction-to-zotero/citations_in_quarto.html - standardise yaml header to YAML header

**Comment by NeuroShepherd** [comment]
Closed in #18
